<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ShopSeeder extends Seeder
{

    public function run()
    {
        $info = array(
            array("title" => "شرکت کالا بهرسان تارا نوین شعبه شیراز", "province_id" => 16, "shop_category_id" => 15, "grade_id" => 4),
            array("title" => "فروشگاه ماف پارس (هایپر استار)  - لواسان", "province_id" => 8, "shop_category_id" => 2, "grade_id" => 4),
            array("title" => "هایپر می اکباتان/ مگامال تهران", "province_id" => 8, "shop_category_id" => 11, "grade_id" => 1),
            array("title" => "هایپرسان نجم خاورمیانه تهران", "province_id" => 8, "shop_category_id" => 4, "grade_id" => 1),
            array("title" => "هایپراستار ارم ( باکری جنوب )", "province_id" => 8, "shop_category_id" => 2, "grade_id" => 1),
            array("title" => "هایپر استار صبا", "province_id" => 8, "shop_category_id" => 2, "grade_id" => 1),
            array("title" => "هایپراستار اصفهان", "province_id" => 4, "shop_category_id" => 2, "grade_id" => 1),
            array("title" => "هایپر استار شیراز", "province_id" => 16, "shop_category_id" => 2, "grade_id" => 1),
            array("title" => "شرکت خدمات کالاي شهروند (لواسان", "province_id" => 8, "shop_category_id" => 1, "grade_id" => 4),
            array("title" => "هایپراستار کوروش (تهران)", "province_id" => 8, "shop_category_id" => 2, "grade_id" => 4),
            array("title" => "هایپر استار تیراژه 2 (تهران)", "province_id" => 8, "shop_category_id" => 2, "grade_id" => 2),
            array("title" => "اتکا شهید امامی نسب (امامی نسب تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 2),
            array("title" => "اتکا شهدای انقلاب (شهدای انقلاب تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "اتکا قصرفیروزه (قصر فیروز تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 2),
            array("title" => "هایپر می سبحان", "province_id" => 8, "shop_category_id" => 11, "grade_id" => 2),
            array("title" => "اتکا فروشگاه شهید دکتر چمران (چمران تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "هایپرسان رشت", "province_id" => 30, "shop_category_id" => 4, "grade_id" => 1),
            array("title" => "اتکا شهید فلاحی (فلاحی تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 2),
            array("title" => "اتکا شهدای سوم خرداد (فلاحی تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا شهید رجایی (رجایی تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "اتکا شهید بروجردی (رجایی تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 2),
            array("title" => "اتکا شهید کوچک افشاری (فلاحی تهران)/اتکا دردشت", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا نوبنیاد (نوبنیاد تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "اتکا شهرک شهید محلاتی (نوبنیاد تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "اتکا شهید کمیل یارمحمدی (کرج)/اتکا کرج", "province_id" => 5, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "اتکا شهدای فردیس (کرج)", "province_id" => 5, "shop_category_id" => 9, "grade_id" => 2),
            array("title" => "اتکا شهید نامجو (نامجو تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "اتکا شهید همتی سمنان (سمنان)", "province_id" => 14, "shop_category_id" => 9, "grade_id" => 2),
            array("title" => "اتکا شهدای مارلیک (کرج)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 2),
            array("title" => "اتکا مهرآباد (مهرآباد تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا توحید (مهرآباد تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "شرکت کالا بهرسان تارا نوین بندرعباس", "province_id" => 22, "shop_category_id" => 15, "grade_id" => 4),
            array("title" => "اتکا شهدای رودهن (شهدای انقلاب تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید فکوری (فکوری تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "اتکا شهدای قم (قم)", "province_id" => 18, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا ولایت (شیراز)", "province_id" => 16, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "اتکا فتح المبین (شیراز)", "province_id" => 16, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "اتکا شهدای ارومیه (ارومیه)", "province_id" => 2, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "اتکا کرمانشاه (کرمانشاه)", "province_id" => 27, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "اتکا شهدای آذربایجان (تبریز)/اتکا تبریز", "province_id" => 1, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "اتکا شهید نظری مهرشهر (کرج)", "province_id" => 5, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا شهید سعادت یار (نوبنیاد تهران)/اتکا لویزان", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 2),
            array("title" => "اتکا شهدای گلستان (گرگان)", "province_id" => 29, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "اتکا شهید مختاری (فلاحی تهران)/اتکا کوهک", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "سی یار گستر ایرانیان-هایپرسی اندیشه 1 (کرج)", "province_id" => 5, "shop_category_id" => 14, "grade_id" => 2),
            array("title" => "اتکا شماره دو گرگان (گرگان)", "province_id" => 29, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا ساری (ساری)", "province_id" => 20, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "اتکا شهدای هرمزگان (بندرعباس)/اتکا بندر عباس", "province_id" => 22, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "اتکا شهید سردار قاسم سلیمانی (اهواز)/اتکا اهواز", "province_id" => 12, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "اتکا شهید ابراهیمی خرم آباد (خرم آباد)", "province_id" => 19, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "اتکا شهید گودرزی بروجرد (خرم آباد)", "province_id" => 19, "shop_category_id" => 9, "grade_id" => 2),
            array("title" => "اورست آل این آل لاله پارک تبریز", "province_id" => 1, "shop_category_id" => 13, "grade_id" => 1),
            array("title" => "اتکا شهدای زرهی (شیراز)", "province_id" => 16, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا کرمان (کرمان)", "province_id" => 26, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "اتکا اراک (اراک)", "province_id" => 21, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "اتکا شهید شهریاری زنجان (زنجان)/اتکا زنجان", "province_id" => 13, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "اتکا قزوین (قزوین)", "province_id" => 17, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "اتکا شهید مدنی همدان (همدان)", "province_id" => 23, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "اتکا ایلام (ایلام)", "province_id" => 6, "shop_category_id" => 9, "grade_id" => 2),
            array("title" => "اتکا شهدای گمنام شهریار (مهرآباد تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 2),
            array("title" => "اتکا گنبد (گرگان)", "province_id" => 29, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا آزادشهر گلستان (گرگان)", "province_id" => 29, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا علی آباد کتول (گرگان)", "province_id" => 29, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "هایپرمی اطلس تبریز", "province_id" => 1, "shop_category_id" => 11, "grade_id" => 1),
            array("title" => "هایپر می پاژ (مشهد)", "province_id" => 10, "shop_category_id" => 11, "grade_id" => 1),
            array("title" => "هایپر می عظیمیه (کرج)", "province_id" => 5, "shop_category_id" => 11, "grade_id" => 1),
            array("title" => "هایپر می اصفهان", "province_id" => 4, "shop_category_id" => 11, "grade_id" => 1),
            array("title" => "هایپر می نمک آبرود(پانوراما)", "province_id" => 20, "shop_category_id" => 11, "grade_id" => 1),
            array("title" => "هایپر می آجودانیه", "province_id" => 8, "shop_category_id" => 11, "grade_id" => 2),
            array("title" => "اتکا هوایی شهید دوران (شیراز)/اتکا هوایی فارس", "province_id" => 16, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا شهدای رشت (رشت)", "province_id" => 30, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "اتکا امام خمینی (نوبنیاد تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای هشتگرد (کرج)", "province_id" => 5, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا سنندج (سنندج)", "province_id" => 25, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "شرکت خدمات کالای شهروند (صادقیه", "province_id" => 8, "shop_category_id" => 1, "grade_id" => 1),
            array("title" => "شرکت خدمات کالای شهروند (بوستان )", "province_id" => 8, "shop_category_id" => 1, "grade_id" => 1),
            array("title" => "شرکت خدمات کالای شهروند (کاشانک", "province_id" => 8, "shop_category_id" => 1, "grade_id" => 3),
            array("title" => "شرکت خدمات کالای شهروند ( آل احمد )", "province_id" => 8, "shop_category_id" => 1, "grade_id" => 2),
            array("title" => "شرکت خدمات کالای شهروند (چیذر )", "province_id" => 8, "shop_category_id" => 1, "grade_id" => 3),
            array("title" => "شرکت خدمات کالای شهروند (بهاران )", "province_id" => 8, "shop_category_id" => 1, "grade_id" => 2),
            array("title" => "شرکت خدمات کالای شهروند (بهرود", "province_id" => 8, "shop_category_id" => 1, "grade_id" => 1),
            array("title" => "شرکت خدمات کالای شهروند (بیهقی", "province_id" => 8, "shop_category_id" => 1, "grade_id" => 1),
            array("title" => "شرکت خدمات کالای شهروند ( آزادگان", "province_id" => 8, "shop_category_id" => 1, "grade_id" => 1),
            array("title" => "شرکت خدمات کالای شهروند(تهران نو )", "province_id" => 8, "shop_category_id" => 1, "grade_id" => 3),
            array("title" => "شرکت خدمات کالای شهروند (لویزان )", "province_id" => 8, "shop_category_id" => 1, "grade_id" => 2),
            array("title" => "شرکت خدمات کالای شهروند( ایران زمین", "province_id" => 8, "shop_category_id" => 1, "grade_id" => 1),
            array("title" => "شرکت خدمات کالای شهروند - (راه آهن", "province_id" => 8, "shop_category_id" => 1, "grade_id" => 4),
            array("title" => "شرکت خدمات کالای شهروند (هفت حوض", "province_id" => 8, "shop_category_id" => 1, "grade_id" => 3),
            array("title" => "شرکت خدمات کالای شهروند( والفجر", "province_id" => 8, "shop_category_id" => 1, "grade_id" => 4),
            array("title" => "شرکت خدمات کالای شهروند (حکیمیه", "province_id" => 8, "shop_category_id" => 1, "grade_id" => 1),
            array("title" => "شرکت خدمات کالای شهروند (شهرری", "province_id" => 8, "shop_category_id" => 1, "grade_id" => 2),
            array("title" => "شرکت خدمات کالای شهروند ( مبعث", "province_id" => 8, "shop_category_id" => 1, "grade_id" => 4),
            array("title" => "شرکت خدمات کالای شهروند( آزادی", "province_id" => 8, "shop_category_id" => 1, "grade_id" => 4),
            array("title" => "شرکت خدمات کالای شهروند (المپیک", "province_id" => 8, "shop_category_id" => 1, "grade_id" => 2),
            array("title" => "اتکا شهدای رستم آباد (رشت)", "province_id" => 30, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "شرکت خدمات کالای شهروند (نبرد )", "province_id" => 8, "shop_category_id" => 1, "grade_id" => 2),
            array("title" => "شرکت خدمات کالای شهروند (متروصادقیه", "province_id" => 8, "shop_category_id" => 1, "grade_id" => 4),
            array("title" => "شرکت خدمات کالای شهروند (خانی آباد", "province_id" => 8, "shop_category_id" => 1, "grade_id" => 2),
            array("title" => "شرکت خدمات کالای شهروند-جنت آباد", "province_id" => 8, "shop_category_id" => 1, "grade_id" => 2),
            array("title" => "اتکا الزهرا (الزهرا اصفهان)", "province_id" => 4, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "هایپراستار پاسداران", "province_id" => 8, "shop_category_id" => 2, "grade_id" => 3),
            array("title" => "شرکت خدمات کالای شهروند( طیب", "province_id" => 8, "shop_category_id" => 1, "grade_id" => 4),
            array("title" => "شرکت خدمات کالای شهروند ( نفت", "province_id" => 8, "shop_category_id" => 1, "grade_id" => 3),
            array("title" => "شرکت خدمات کالای شهروند (ملک", "province_id" => 8, "shop_category_id" => 1, "grade_id" => 3),
            array("title" => "اتکا شهید رییسعلی دلواری (بوشهر)/اتکا بوشهر", "province_id" => 7, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "اتکا یاسوج (یاسوج)", "province_id" => 28, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "شرکت خدمات کالای شهروند ( دارآباد", "province_id" => 8, "shop_category_id" => 1, "grade_id" => 4),
            array("title" => "اتکا شهدای غواص (فکوری تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 2),
            array("title" => "شرکت خدمات کالای شهروند (لواسان", "province_id" => 8, "shop_category_id" => 1, "grade_id" => 4),
            array("title" => "اتکا دو هزار واحدی (رجایی تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا پارچین (رجایی تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید رستمی (بجنورد)/اتکا بجنورد", "province_id" => 11, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "هایپرمی هاشمیه مشهد", "province_id" => 10, "shop_category_id" => 11, "grade_id" => 1),
            array("title" => "هایپرمی سنتر خزر تنکابن", "province_id" => 20, "shop_category_id" => 11, "grade_id" => 1),
            array("title" => "شرکت خدمات کالای شهروند (پرند", "province_id" => 8, "shop_category_id" => 1, "grade_id" => 3),
            array("title" => "شرکت خدمات کالای شهروند (عدل", "province_id" => 8, "shop_category_id" => 1, "grade_id" => 4),
            array("title" => "هایپرمی طوبی", "province_id" => 8, "shop_category_id" => 11, "grade_id" => 2),
            array("title" => "اتکا یزد (یزد)", "province_id" => 31, "shop_category_id" => 9, "grade_id" => 2),
            array("title" => "اتکا ولیعصر نسیم شهر (مهرآباد تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "شرکت خدمات کالای شهروند(تهرانسر", "province_id" => 8, "shop_category_id" => 1, "grade_id" => 3),
            array("title" => "هایپرمی نیکامال", "province_id" => 5, "shop_category_id" => 11, "grade_id" => 3),
            array("title" => "اتکا شهدای گمنام رباط کریم (مهرآباد تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "هایپرمی آمل", "province_id" => 20, "shop_category_id" => 11, "grade_id" => 3),
            array("title" => "اتکا اردبیل (اردبیل)", "province_id" => 3, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "اتکا پایگاه هوایی تبریز (تبریز)", "province_id" => 1, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا مرند (تبریز)", "province_id" => 1, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا شهدای مراغه (مراغه)", "province_id" => 1, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "فروشگاه سپه (رودکی )", "province_id" => 8, "shop_category_id" => 10, "grade_id" => 4),
            array("title" => "اتکا خاورشهر (رجایی تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "فروشگاه سپه (آزادی)", "province_id" => 8, "shop_category_id" => 10, "grade_id" => 4),
            array("title" => "فروشگاه سپه (ویلا)", "province_id" => 8, "shop_category_id" => 10, "grade_id" => 4),
            array("title" => "اتکا شهید کاظم بازیار (بندرعباس)/اتکا امام علی", "province_id" => 22, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "فروشگاه سپه (پیروزی )", "province_id" => 8, "shop_category_id" => 10, "grade_id" => 4),
            array("title" => "فروشگاه سپه (دولت )", "province_id" => 8, "shop_category_id" => 10, "grade_id" => 4),
            array("title" => "فروشگاه سپه (شریف )", "province_id" => 8, "shop_category_id" => 10, "grade_id" => 4),
            array("title" => "فروشگاه سپه کرج", "province_id" => 5, "shop_category_id" => 10, "grade_id" => 4),
            array("title" => "اتکا اتکا یاغچیان (تبریز)/اتکا گلشهر", "province_id" => 1, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا شهدای سهند (تبریز)", "province_id" => 1, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا شهرکرد (شهرکرد)", "province_id" => 24, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "اتکا سخایی(پیشوا)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 2),
            array("title" => "اتکا شهدای آستانه اشرفیه (رشت)", "province_id" => 30, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا لاهیجان (رشت)", "province_id" => 30, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا لنگرود (رشت)", "province_id" => 30, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای بندر انزلی (رشت)", "province_id" => 30, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "اتکا شهدای رودسر (رشت)", "province_id" => 30, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای اندیشه (مهرآباد تهران)", "province_id" => 5, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا ورامین (پیشوا)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا تنکابن (ساری)", "province_id" => 20, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای ماسال (رشت)", "province_id" => 30, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای صومعه سرا (رشت)", "province_id" => 30, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "هایپراستار رباط کریم", "province_id" => 8, "shop_category_id" => 2, "grade_id" => 3),
            array("title" => "اتکا شهید زرهرن شاهرود (سمنان)", "province_id" => 14, "shop_category_id" => 9, "grade_id" => 2),
            array("title" => "اتکا ساوه (اراک)", "province_id" => 21, "shop_category_id" => 9, "grade_id" => 2),
            array("title" => "هایپرمی مهرشهر ( کرج)", "province_id" => 5, "shop_category_id" => 11, "grade_id" => 3),
            array("title" => "اتکا شهید کاوه بیرجند (بیرجند)", "province_id" => 9, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "اتکا شهدای اصفهان (الزهرا اصفهان)", "province_id" => 4, "shop_category_id" => 9, "grade_id" => 2),
            array("title" => "اتکا شاهین شهر (الزهرا اصفهان)", "province_id" => 4, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "اتکا نجف آباد (الزهرا اصفهان)", "province_id" => 4, "shop_category_id" => 9, "grade_id" => 2),
            array("title" => "اتکا شهدای گرمسار (سمنان)", "province_id" => 14, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای رحیمی دزفول (اهواز)", "province_id" => 12, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "اتکا بعثت خرمشهر (اهواز)", "province_id" => 12, "shop_category_id" => 9, "grade_id" => 2),
            array("title" => "اتکا صاحب الامر (الزهرا اصفهان)", "province_id" => 4, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "هایپرمی فردیس", "province_id" => 5, "shop_category_id" => 11, "grade_id" => 2),
            array("title" => "هایپراستار افرا", "province_id" => 8, "shop_category_id" => 2, "grade_id" => 3),
            array("title" => "اتکا شعبه دو زنجان (زنجان)", "province_id" => 13, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "اتکا شهدای ماهشهر (اهواز)", "province_id" => 12, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "فامیلی مدرن گنبد (گلستان)", "province_id" => 29, "shop_category_id" => 7, "grade_id" => 4),
            array("title" => "اتکا بهارستان (الزهرا اصفهان)", "province_id" => 4, "shop_category_id" => 9, "grade_id" => 2),
            array("title" => "اتکا قائم شهر (ساری)", "province_id" => 20, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "هایپراستار جماران", "province_id" => 8, "shop_category_id" => 2, "grade_id" => 3),
            array("title" => "اتکا صدرا (شیراز)", "province_id" => 16, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "اتکا بیست و یک حمزه (تبریز)", "province_id" => 1, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا میانه (تبریز)", "province_id" => 1, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا سراب (تبریز)", "province_id" => 1, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا زعفرانیه (تبریز)", "province_id" => 1, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا آمل (ساری)", "province_id" => 20, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا شهید مرادپور (اهواز)/اتکا شوشتر", "province_id" => 12, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا شهدای آباده (شیراز)", "province_id" => 16, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "سی یار گستر ایرانیان-هایپرسی اندیشه 2 (کرج)", "province_id" => 8, "shop_category_id" => 14, "grade_id" => 4),
            array("title" => "اتکا اهر (تبریز)", "province_id" => 1, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "فامیلی مدرن شاندیز مشهد", "province_id" => 10, "shop_category_id" => 7, "grade_id" => 3),
            array("title" => "پلاس وان مشهد", "province_id" => 10, "shop_category_id" => 8, "grade_id" => 4),
            array("title" => "اتکا یاس (نامجو تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای گمنام پرند (مهرآباد تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا شهید درخشان (مهرآباد تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا الغدیر (قم)", "province_id" => 18, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "اتکا بابل (ساری)", "province_id" => 20, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا چالوس (ساری)", "province_id" => 20, "shop_category_id" => 9, "grade_id" => 2),
            array("title" => "اتکا نوهد (مهرآباد تهران)/اتکا پرندک", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای بهبهان (اهواز)", "province_id" => 12, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شبستر (تبریز)", "province_id" => 1, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا بم (کرمان)", "province_id" => 26, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا سیرجان (کرمان)", "province_id" => 26, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا هوانیروز (کرمان)", "province_id" => 26, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا ابهر (زنجان)", "province_id" => 13, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شماره دو بروجرد (خرم آباد)", "province_id" => 19, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا شهید شوشتری (زاهدان)/اتکا مرکزی زاهدان (زاهدان)", "province_id" => 15, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "اتکا شهید ستوده فسا (شیراز)", "province_id" => 16, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا امیرکبیر کاشان (الزهرا اصفهان)", "province_id" => 4, "shop_category_id" => 9, "grade_id" => 2),
            array("title" => "فامیلی مدرن امام خمینی(قم)", "province_id" => 18, "shop_category_id" => 7, "grade_id" => 3),
            array("title" => "اتکا شهید جولائی (امامی نسب تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شاهرود2 (سمنان)", "province_id" => 14, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهرک آزادی (فکوری تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا جام جم (تبریز)", "province_id" => 1, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا حکیمیه (قصر فیروز تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای لشگر (سنندج)/اتکا سنندج2", "province_id" => 25, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید فلاحی مشهد (مشهد)", "province_id" => 10, "shop_category_id" => 9, "grade_id" => 2),
            array("title" => "سپه حر", "province_id" => 8, "shop_category_id" => 10, "grade_id" => 4),
            array("title" => "اتکا شهید تهرانی مقدم (نوبنیاد تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا محلات (اراک)", "province_id" => 21, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "هایپر استار یزد", "province_id" => 31, "shop_category_id" => 2, "grade_id" => 2),
            array("title" => "اتکا شهدای یاسوج (یاسوج)", "province_id" => 28, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا دلیجان (راک)", "province_id" => 21, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا مهاباد (ارومیه)", "province_id" => 2, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "هایپر استار اکومال (کرج)", "province_id" => 5, "shop_category_id" => 2, "grade_id" => 1),
            array("title" => "اتکا اشرفی اصفهانی2 (الزهرا اصفهان)", "province_id" => 4, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "اتکا شهید ستاری قرچک - سامان (پیشوا)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "فامیلی مدرن سمنان", "province_id" => 14, "shop_category_id" => 7, "grade_id" => 3),
            array("title" => "اتکا شهدای گلپایگان (الزهرا اصفهان)", "province_id" => 4, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا داران (الزهرا اصفهان)", "province_id" => 4, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا ولیعصر (مراغه)", "province_id" => 1, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا عجبشیر (مراغه)", "province_id" => 1, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا ملکان (مراغه)", "province_id" => 1, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهرضا (الزهرا اصفهان)", "province_id" => 4, "shop_category_id" => 9, "grade_id" => 2),
            array("title" => "اتکا شهید ناخدا همتی (بوشهر)/اتکا دریایی ارتش", "province_id" => 7, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای بناب (مراغه)", "province_id" => 1, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا آبادان (اهواز)", "province_id" => 12, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید فلاحی مسجدسلیمان (اهواز)", "province_id" => 12, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا کلاچای (رشت)", "province_id" => 30, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا رشت2 (رشت)", "province_id" => 30, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "فامیلی مدرن بجنورد", "province_id" => 11, "shop_category_id" => 7, "grade_id" => 3),
            array("title" => "اتکا شهدای تالش (رشت)", "province_id" => 30, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "شرکت خدمات کالای شهروند(تهرانپارس)", "province_id" => 8, "shop_category_id" => 1, "grade_id" => 4),
            array("title" => "هایپراستار ایران مال", "province_id" => 8, "shop_category_id" => 2, "grade_id" => 1),
            array("title" => "هایپرفامیلی مشهد آرلتون", "province_id" => 10, "shop_category_id" => 7, "grade_id" => 4),
            array("title" => "اتکا شهید خلبان بابایی (بوشهر)/اتکا هوایی", "province_id" => 7, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا خمین (اراک)", "province_id" => 21, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "فروشگاه فامیلی مدرن یزد", "province_id" => 31, "shop_category_id" => 7, "grade_id" => 3),
            array("title" => "اتکا شهدای رامهرمز (اهواز)", "province_id" => 12, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا سوسنگرد (اهواز)", "province_id" => 12, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "هایپرمی  کیا مال", "province_id" => 5, "shop_category_id" => 11, "grade_id" => 1),
            array("title" => "اتکا کازرون (شیراز)", "province_id" => 16, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "هایپرمی فرشته", "province_id" => 8, "shop_category_id" => 11, "grade_id" => 3),
            array("title" => "اتکا اردستان (الزهرا اصفهان)", "province_id" => 4, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "سی یار گستر ایرانیان-هایپرسی شهریار", "province_id" => 5, "shop_category_id" => 14, "grade_id" => 3),
            array("title" => "اتکا ثامن الحجج (مشهد)/اتکا مرکزی مشهد", "province_id" => 10, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "اتکا جهرم (شیراز)", "province_id" => 16, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "فامیلی مدرن قم شعبه 2", "province_id" => 18, "shop_category_id" => 7, "grade_id" => 4),
            array("title" => "شهروند دروس (شرکت خدماتی کالای شهروند)", "province_id" => 8, "shop_category_id" => 1, "grade_id" => 4),
            array("title" => "فامیلی مدرن پروما مشهد", "province_id" => 10, "shop_category_id" => 7, "grade_id" => 3),
            array("title" => "اتکا ساری2 (ساری)", "province_id" => 20, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا نور (ساری)", "province_id" => 20, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا بابلسر (ساری)", "province_id" => 20, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا ایرانشهر (زاهدان)", "province_id" => 15, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا پایگاه هوایی کنارک (سیستان و بلوچستان)/ شعبه1", "province_id" => 15, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا پایگاه دریایی کنارک (سیستان و بلوچستان)/ شعبه2", "province_id" => 15, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا چابهار (سیستان و بلوچستان)", "province_id" => 15, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "فامیلی مدرن فریدون کنار", "province_id" => 20, "shop_category_id" => 7, "grade_id" => 4),
            array("title" => "هایپرمی پارسه (تهران)", "province_id" => 8, "shop_category_id" => 11, "grade_id" => 3),
            array("title" => "اتکا شهدای ارتش کرمانشاه (کرمانشاه)", "province_id" => 27, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "اتکا سلماس (ارومیه)", "province_id" => 2, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا آذرشهر (تبریز)", "province_id" => 1, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا خرمدره (زنجان)", "province_id" => 13, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا گچساران (یاسوج)", "province_id" => 28, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا دهدشت (یاسوج)", "province_id" => 28, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا زابل (سیستان و بلوچستان)", "province_id" => 15, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا سقز (سنندج)", "province_id" => 25, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا بانه (سنندج)", "province_id" => 25, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید ورمقانی (سنندج)/اتکا قروه", "province_id" => 25, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا شهدای بیجار (سنندج)", "province_id" => 25, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا کامیاران (سنندج)", "province_id" => 25, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا مریوان (سنندج)", "province_id" => 25, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا بانه 2 (سنندج)", "province_id" => 25, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا دیوان دره (سنندج)", "province_id" => 25, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای سریش آباد (سنندج)", "province_id" => 25, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهرک باغمیشه (تبریز)", "province_id" => 1, "shop_category_id" => 9, "grade_id" => 2),
            array("title" => "اتکا ایلخچی (تبریز)", "province_id" => 1, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای خطیب (تبریز)", "province_id" => 1, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "فامیلی مدرن نیشابور", "province_id" => 10, "shop_category_id" => 7, "grade_id" => 3),
            array("title" => "اتکا لشگر (کرمانشاه)", "province_id" => 27, "shop_category_id" => 9, "grade_id" => 2),
            array("title" => "اتکا پایگاه هوایی شهید بابایی (الزهرا اصفهان)", "province_id" => 4, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا میبد (یزد)", "province_id" => 31, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا لاله غربی (تبریز)", "province_id" => 1, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا صوفیان (تبریز)", "province_id" => 1, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شاهین دژ (ارومیه)", "province_id" => 2, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا میاندوآب (ارومیه)", "province_id" => 2, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا گلشهر (مراغه)", "province_id" => 1, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای عجبشیر (مراغه)", "province_id" => 1, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "فامیلی ساعی خمینی شهر اصفهان", "province_id" => 4, "shop_category_id" => 7, "grade_id" => 4),
            array("title" => "اتکا شهدای باغملک (اهواز)", "province_id" => 12, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا بیمارستان شریعتی (نامجو تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا برازجان (بوشهر)", "province_id" => 7, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "فامیلی مدرن مبارکه اصفهان", "province_id" => 4, "shop_category_id" => 7, "grade_id" => 4),
            array("title" => "اتکا شهدای شیروان (مشهد)", "province_id" => 10, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "فروشگاه  فامیلی امام علی", "province_id" => 31, "shop_category_id" => 7, "grade_id" => 3),
            array("title" => "فامیلی مدرن دشتی (یزد)", "province_id" => 31, "shop_category_id" => 7, "grade_id" => 4),
            array("title" => "اتکا شهدای کمالشهر (کرج)", "province_id" => 5, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "فامیلی مدرن دانشجو (یزد)", "province_id" => 31, "shop_category_id" => 7, "grade_id" => 4),
            array("title" => "فامیلی مدرن دهه فجر (یزد)", "province_id" => 31, "shop_category_id" => 7, "grade_id" => 3),
            array("title" => "اتکا ملایر (همدان)", "province_id" => 23, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای نهاوند (همدان)", "province_id" => 23, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید نوژه (همدان)", "province_id" => 23, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا مولوی (ارومیه)", "province_id" => 2, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا بعثت (ارومیه)", "province_id" => 2, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا ظفر (کرمانشاه)", "province_id" => 27, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا شهرک پردیس (کرمانشاه)", "province_id" => 27, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا گیلانغرب (کرمانشاه)", "province_id" => 27, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا هوانیروز کرمانشاه (کرمانشاه)", "province_id" => 27, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید شیرودی (کرمانشاه)/اتکا هرسین", "province_id" => 27, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا اسلام آباد غرب (کرمانشاه)", "province_id" => 27, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا جانبازان پاوه (کرمانشاه)", "province_id" => 27, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا سنقر (کرمانشاه)", "province_id" => 27, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای صحنه (کرمانشاه)", "province_id" => 27, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای جوانرود (کرمانشاه)", "province_id" => 27, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا کنگاور (کرمانشاه)", "province_id" => 27, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای چالدران (ارومیه)", "province_id" => 2, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا فاطمی (کرج)", "province_id" => 5, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا بعثت (کرج)", "province_id" => 5, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا همایون ویلا (کرج)", "province_id" => 5, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا امیرکبیر (کرج)/اتکا کیانمهر", "province_id" => 5, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "هایپراستار اوپال", "province_id" => 8, "shop_category_id" => 2, "grade_id" => 2),
            array("title" => "اتکا قائم (کرج)/اتکا گوهردشت", "province_id" => 5, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا بروجرد3 (خرم آباد)", "province_id" => 19, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "فامیلی مدرن قوچان", "province_id" => 10, "shop_category_id" => 7, "grade_id" => 4),
            array("title" => "فامیلی مدرن کیانی", "province_id" => 4, "shop_category_id" => 7, "grade_id" => 4),
            array("title" => "اتکا قیدار (زنجان)", "province_id" => 13, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "فامیلی مدرن گرمدره", "province_id" => 5, "shop_category_id" => 7, "grade_id" => 3),
            array("title" => "اتکا شهدای بابلسر (ساری)", "province_id" => 20, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "شهروند شمیران سنتر(شرکت خدماتی کالای شهروند)", "province_id" => 8, "shop_category_id" => 1, "grade_id" => 4),
            array("title" => "اتکا شهدای بازارچه سیلاب (تبریز)", "province_id" => 1, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "شهروند مهرشهر(شرکت خدماتی کالای شهروند)", "province_id" => 5, "shop_category_id" => 1, "grade_id" => 2),
            array("title" => "اتکا شهدا باشت (یاسوج)", "province_id" => 28, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدا دهدشت (یاسوج)", "province_id" => 28, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "هایپراستار  تهران پارس", "province_id" => 8, "shop_category_id" => 2, "grade_id" => 2),
            array("title" => "اتکا شهدای گچساران (یاسوج)", "province_id" => 28, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای بهمئی (یاسوج)", "province_id" => 28, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا ایلام2 (ایلام)", "province_id" => 6, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا ولیعصر (ایلام)", "province_id" => 6, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا عبدالصباح امینیان (ایلام)", "province_id" => 6, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید محمد نبی شمسی (ایلام)", "province_id" => 6, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید حیدر قلی ربیعی سرابله (ایلام)", "province_id" => 6, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای ایوانغرب (ایلام)", "province_id" => 6, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای آبدانان (ایلام)", "province_id" => 6, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید مرادی (رجایی تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا بهشهر (ساری)", "province_id" => 20, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید توسلی خورموج (بوشهر)", "province_id" => 7, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای مال خلیفه (یاسوج)", "province_id" => 28, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا سرو آباد (سنندج)", "province_id" => 25, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا آل محمد (الزهرا اصفهان)", "province_id" => 4, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا شهدای روانسر (کرمانشاه)", "province_id" => 27, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "فامیلی مدرن شهر ری", "province_id" => 8, "shop_category_id" => 7, "grade_id" => 4),
            array("title" => "اتکا شهدای مرودشت (شیراز)", "province_id" => 16, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای ارسنجان (شیراز)", "province_id" => 16, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا زیتون کارمندی (اهواز)", "province_id" => 12, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا هلال بهبهان (اهواز)", "province_id" => 12, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا قوچان (مشهد)", "province_id" => 10, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا شهید احمدی جوان (بوشهر)/اتکا عالیشهر", "province_id" => 7, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "فروشگاه امیران( حصارک)", "province_id" => 5, "shop_category_id" => 5, "grade_id" => 5),
            array("title" => "فروشگاه امیران(فردیس)", "province_id" => 5, "shop_category_id" => 5, "grade_id" => 6),
            array("title" => "فروشگاه امیران(کردان)", "province_id" => 5, "shop_category_id" => 5, "grade_id" => 5),
            array("title" => "اتکا نیشابور (مشهد)", "province_id" => 10, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا شهدای خوانسار (الزهرا اصفهان)", "province_id" => 4, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا گناباد (مشهد)", "province_id" => 10, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای نکا (ساری)", "province_id" => 20, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا قاسم ابن الحسن (شهدای انقلاب تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید شیردل (مشهد)", "province_id" => 10, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای هفتکل (اهواز)", "province_id" => 12, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید علی لندی (اهواز)/اتکا ایذه", "province_id" => 12, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای پدافند هوایی (مشهد)/اتکا رادار", "province_id" => 10, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا زرند (کرمان)", "province_id" => 26, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای هشترود (مراغه)", "province_id" => 1, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید برونسی (مشهد)/اتکا تربت حیدریه (مشهد)", "province_id" => 10, "shop_category_id" => 9, "grade_id" => 2),
            array("title" => "فروشگاه زنجیره امیران(بلوارارم)", "province_id" => 5, "shop_category_id" => 5, "grade_id" => 6),
            array("title" => "فروشگاه امیران(فاز 4 مهرشهر )", "province_id" => 5, "shop_category_id" => 5, "grade_id" => 5),
            array("title" => "فروشگاه امیران (فرهنگیان-خیابان قزوین)", "province_id" => 5, "shop_category_id" => 5, "grade_id" => 5),
            array("title" => "فروشگاه امیران (فاز 1 اندیشه)", "province_id" => 5, "shop_category_id" => 5, "grade_id" => 6),
            array("title" => "فروشگاه امیران (مهرشهر)", "province_id" => 5, "shop_category_id" => 5, "grade_id" => 5),
            array("title" => "فروشگاه امیران (بلوار انقلاب)", "province_id" => 5, "shop_category_id" => 5, "grade_id" => 5),
            array("title" => "فروشگاه امیران (عظیمیه-میخک)", "province_id" => 5, "shop_category_id" => 5, "grade_id" => 6),
            array("title" => "فروشگاه امیران (باغستان)", "province_id" => 5, "shop_category_id" => 5, "grade_id" => 5),
            array("title" => "اتکا شهید وطن یاری (اهواز)/اتکا دشت آزادگان", "province_id" => 12, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید قهرمانی (بندرعباس)/اتکا هدیش", "province_id" => 22, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا شهدای خسروشاه (تبریز)", "province_id" => 1, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا الهیه کرمانشاه (کرمانشاه)", "province_id" => 27, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا شهدای نورآباد (شیراز)", "province_id" => 16, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا فجر (تبریز)", "province_id" => 1, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای میانه2 (تبریز)", "province_id" => 1, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا هوا نیروز (الزهرا اصفهان)", "province_id" => 4, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا امام خمینی زرین شهر (الزهرا اصفهان)", "province_id" => 4, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "فروشگاه زنجیره ای امیران(مشکین دشت)", "province_id" => 5, "shop_category_id" => 5, "grade_id" => 5),
            array("title" => "اتکا شهرک فرهنگیان (ارومیه)", "province_id" => 2, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "امیران ملارد(دفتر مرکزی)", "province_id" => 8, "shop_category_id" => 5, "grade_id" => 5),
            array("title" => "اتکا قلم (کرج)", "province_id" => 5, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای قشم (قشم)", "province_id" => 22, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "فامیلی مدرن الغدیر (اصفهان)", "province_id" => 4, "shop_category_id" => 7, "grade_id" => 3),
            array("title" => "اتکا پاکدشت (پیشوا)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "فروشگاه امیران(درختی)", "province_id" => 5, "shop_category_id" => 5, "grade_id" => 6),
            array("title" => "اتکا گیلاوند (شهدای انقلاب تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا مسکن (کرمانشاه)", "province_id" => 27, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا سراوان (سیستان و بلوچستان)", "province_id" => 15, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "هایپر استار قم", "province_id" => 18, "shop_category_id" => 2, "grade_id" => 1),
            array("title" => "اتکا شهدای سقز (سنندج)", "province_id" => 25, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا ستاد کل (فلاحی تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید زنگنه (کرج)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا گلوگاه (ساری)", "province_id" => 20, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای جهرم (شیراز)", "province_id" => 16, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید اخلاص طلب (بندرعباس)/اتکا هوایی", "province_id" => 22, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای خلیج فارس (بوشهر)/اتکا ریشهر", "province_id" => 7, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا شهدای تکاب (ارومیه)", "province_id" => 2, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا فاز 4 مهرشهر (کرج)", "province_id" => 5, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "فامیلی مدرن کرمان", "province_id" => 26, "shop_category_id" => 7, "grade_id" => 3),
            array("title" => "اتکا بلوار کشاورز (ساری)", "province_id" => 20, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید حامدی (مشهد)", "province_id" => 10, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا ماهدشت (کرج)", "province_id" => 5, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "هایپراستار مارلیک (کرج)", "province_id" => 5, "shop_category_id" => 2, "grade_id" => 1),
            array("title" => "اتکا کاشمر (مشهد)", "province_id" => 10, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا گلشهر (زنجان)", "province_id" => 13, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا فارسان (شهرکرد)", "province_id" => 24, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید علیزاده دامغان (سمنان)", "province_id" => 14, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید دانشگر سمنان (سمنان)", "province_id" => 14, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا رسالت (کرمانشاه)", "province_id" => 27, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا میناب (بندرعباس)", "province_id" => 22, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا مطهری رودهن (نوبنیاد تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید ورمزیار (ارومیه)", "province_id" => 2, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای اندیمشک(اهواز)", "province_id" => 12, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا نصر (کرمانشاه)", "province_id" => 27, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای مبارکه (الزهرا اصفهان)", "province_id" => 4, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا حافظ اسلامشهر (اتکا رجایی)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا سبزوار (مشهد)", "province_id" => 10, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا ثامن الحجج(مشهد)", "province_id" => 10, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا جیرفت (کرمان)", "province_id" => 26, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای دامغان (سمنان)", "province_id" => 14, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای سبزوار (مشهد)", "province_id" => 10, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا شهدای نیرو انتظامی (اتکا نامجو)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا امامت مشهد (مشهد)", "province_id" => 10, "shop_category_id" => 9, "grade_id" => 2),
            array("title" => "اتکا شهدای پارس آباد (اردبیل)", "province_id" => 3, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای کیش (بندر عباس)", "province_id" => 22, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید صیاد شیرازی (کرمانشاه)", "province_id" => 27, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای کنگان (بوشهر)", "province_id" => 7, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا شهدای رودان (بندرعباس)", "province_id" => 22, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای بندر لنگه (بندر عباس)", "province_id" => 22, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای نطنز (اصفهان)", "province_id" => 4, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا جاسک (بندر عباس)", "province_id" => 22, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای فسا فرانچایز (شیراز)", "province_id" => 16, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "فامیلی مدرن بابل", "province_id" => 20, "shop_category_id" => 7, "grade_id" => 2),
            array("title" => "اتکا طالقانی کرمانشاه (کرمانشاه)", "province_id" => 27, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید محبعلی فارسی (سیستان و بلوچستان)", "province_id" => 15, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا کردکوی (گرگان)", "province_id" => 29, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید واحدی (کرمانشاه)", "province_id" => 27, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا سپیدار (اهواز)", "province_id" => 12, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا گاوگان (تبریز)", "province_id" => 1, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا مهر سهند (تبریز)", "province_id" => 1, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای تنگستان اهرم (بوشهر)", "province_id" => 7, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا بهاران (سنندج)", "province_id" => 25, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا اندیشه زنجان (زنجان)", "province_id" => 13, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا ابهر 2 (زنجان)", "province_id" => 13, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای یکه دکان (تبریز)", "province_id" => 1, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا امام حسن داراب (شیراز)", "province_id" => 16, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا دانشگاه (نوبنیاد تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید کاظمی (نوبنیاد تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا فردوسی نیشابور (مشهد)", "province_id" => 10, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا کریمی (اراک)", "province_id" => 21, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا خاش (زاهدان)", "province_id" => 15, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا مشگین شهر (اردبیل)", "province_id" => 3, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا میرجاوه (زاهدان)", "province_id" => 15, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای وحدت (زاهدان)/اتکا وحدت زابل", "province_id" => 15, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "هایپراستار (ارومیه)", "province_id" => 2, "shop_category_id" => 2, "grade_id" => 1),
            array("title" => "اتکا شهید ساوجی (کرج)", "province_id" => 5, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا الهیه مشهد (مشهد)", "province_id" => 10, "shop_category_id" => 9, "grade_id" => 2),
            array("title" => "اتکا سپاه (سنندج)", "province_id" => 25, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای مهرویلا (کرج)", "province_id" => 5, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا مایان (تبریز)", "province_id" => 1, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهرک صابر (مهرآباد)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا امام رضا (شهدای انقلاب تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا حاجیان (پیشوا)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا آبیک (قزوین)/اتکا ایرج عیوضی", "province_id" => 17, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا شهدای پرواز (اصفهان)", "province_id" => 4, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا جوادالائمه (اصفهان)", "province_id" => 4, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا فدک (بوشهر)", "province_id" => 7, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "فامیلی مدرن شریعتی (تهران)", "province_id" => 8, "shop_category_id" => 7, "grade_id" => 4),
            array("title" => "اتکا شهرک امید (نوبنیاد تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا گنجینه کیش (بندرعباس)", "province_id" => 22, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا شهدای کوچصفهان (رشت)", "province_id" => 30, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا روانسر2 (کرمانشاه)", "province_id" => 27, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "فامیلی مدرن (تبریز)", "province_id" => 1, "shop_category_id" => 7, "grade_id" => 4),
            array("title" => "اتکا شهدای مزرعه نمونه (گرگان)", "province_id" => 29, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای مینو دشت (گرگان)", "province_id" => 29, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای گالیکش (گرگان)", "province_id" => 29, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا ولیعصر 2 (مراغه)", "province_id" => 1, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا آشخانه (بجنورد)", "province_id" => 11, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای پیرانشهر (ارومیه)", "province_id" => 2, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا اصلاندوز (اردبیل)", "province_id" => 3, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا پارس آباد 2 (اردبیل)", "province_id" => 3, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا نقده (ارومیه)", "province_id" => 2, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا کوثر (شهدای انقلاب تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهرک شهید بهشتی (نوبنیاد تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا شهید باقری (قزوین)", "province_id" => 17, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "فامیلی مدرن امیرکبیر (کاشان)", "province_id" => 4, "shop_category_id" => 7, "grade_id" => 3),
            array("title" => "اتکا هامون (زاهدان)", "province_id" => 15, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شازند (اراک)", "province_id" => 21, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شیخ نوایی (ارومیه)", "province_id" => 2, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "هایپراستار بوتانیکال (مشهد)", "province_id" => 10, "shop_category_id" => 2, "grade_id" => 4),
            array("title" => "اتکا شهدای اروند آبادان(اهواز)", "province_id" => 12, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا وحدت گنبد (گرگان)", "province_id" => 29, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید صفوی (بوشهر)", "province_id" => 7, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا شهید زواری (رجایی تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا بهداری (کرمانشاه)", "province_id" => 27, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا ثامن (فلاحی تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا صدا و سیما (نامجو تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا هاشمیه مشهد (مشهد)", "province_id" => 10, "shop_category_id" => 9, "grade_id" => 2),
            array("title" => "اتکا شهید سلیمانی هشتگرد (کرج)", "province_id" => 5, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا لنگرود 1 (رشت)", "province_id" => 30, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا خوی (ارومیه)", "province_id" => 2, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "فامیلی مدرن (بناب)", "province_id" => 1, "shop_category_id" => 7, "grade_id" => 4),
            array("title" => "اتکا شهدای نمین (اردبیل)", "province_id" => 3, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا کیاشهر (رشت)", "province_id" => 30, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا نجیرم (بوشهر)", "province_id" => 7, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا محمود آباد (ساری)", "province_id" => 20, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا ماندستان (بوشهر)", "province_id" => 7, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا چمستان (ساری)", "province_id" => 20, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا دهگلان (سنندج)", "province_id" => 25, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "هایپرمی محمودآباد (مازندران)", "province_id" => 20, "shop_category_id" => 11, "grade_id" => 4),
            array("title" => "اتکا شهدای جویبار (ساری)", "province_id" => 20, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "هایپراستار (قزوین)", "province_id" => 17, "shop_category_id" => 2, "grade_id" => 3),
            array("title" => "اتکا سلمان فارسی (کرمانشاه)", "province_id" => 27, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای املش (رشت)", "province_id" => 30, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهرقدس (فکوری تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "فامیلی مدرن سیرجان (کرمان)", "province_id" => 26, "shop_category_id" => 7, "grade_id" => 3),
            array("title" => "اتکا جامی سنندج (سنندج)", "province_id" => 25, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا بروجن (شهرکرد)", "province_id" => 24, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید دقایقی (اهواز)", "province_id" => 12, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا کهنوج (کرمان)", "province_id" => 26, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای پلدشت (ارومیه)", "province_id" => 2, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای ماکو (ارومیه)", "province_id" => 2, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا جوادآباد -سامان (پیشوا)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید حسینی سرخس (مشهد)", "province_id" => 10, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای پردیس (شهدای انقلاب)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "فامیلی مدرن (قم)", "province_id" => 18, "shop_category_id" => 7, "grade_id" => 3),
            array("title" => "اتکا شهدای سلامت (قزوین)", "province_id" => 17, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای کلاله (گرگان)", "province_id" => 29, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "هایپرمی اردبیل (اردبیل)", "province_id" => 3, "shop_category_id" => 11, "grade_id" => 1),
            array("title" => "اتکا اندیشه مشهد (مشهد)", "province_id" => 10, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای رفسنجان (کرمان)", "province_id" => 26, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای فومن (رشت)", "province_id" => 30, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای ارتش (کرج)", "province_id" => 5, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "شرکت خدماتی کالای شهروند(بهشت)", "province_id" => 8, "shop_category_id" => 1, "grade_id" => 4),
            array("title" => "اتکا ولایت خرم آباد (خرم آباد)", "province_id" => 19, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا میدان امام حسین (خرم آباد)", "province_id" => 19, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا قائم کرمانشاه (کرمانشاه)", "province_id" => 27, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای حاجی آباد (بندرعباس)", "province_id" => 22, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای گمنام(نوبنیاد تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا شهدای دشتستان برازجان(بوشهر)", "province_id" => 7, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا  فارابی (نامجو)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای فاضل آباد(گرگان)", "province_id" => 29, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید فلاح نژاد (فکوری تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا پردیس اهواز (اهواز)", "province_id" => 12, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای فریدونکنار(ساری)", "province_id" => 20, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "هایپراستار هدیش(تهران)", "province_id" => 8, "shop_category_id" => 2, "grade_id" => 4),
            array("title" => "اتکا شهدای خان ببین (گرگان)", "province_id" => 29, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا امام خمینی ماهشهر (اهواز)/اتکا مشارکتی", "province_id" => 12, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا طب کودکان(اتکا نامجو)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "فامیلی مدرن زاهدان(زاهدان)", "province_id" => 15, "shop_category_id" => 7, "grade_id" => 3),
            array("title" => "فامیلی رفسنجان(کرمان)", "province_id" => 26, "shop_category_id" => 7, "grade_id" => 3),
            array("title" => "اتکا شهدای نوشهر(ساری)", "province_id" => 20, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا بهروش (ارومیه)", "province_id" => 2, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا گلستان( شهید یاسینی)(امامی نسب)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای اکبرآباد(شیراز)", "province_id" => 16, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا نیکشهر فرانچایز(زاهدان)", "province_id" => 15, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید بابائی (قزوین)/اتکا محمدیه", "province_id" => 17, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا اندیشه (تبریز)", "province_id" => 1, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای قائمشهر(ساری)", "province_id" => 20, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید ابراهیم هادی (کرمانشاه)", "province_id" => 27, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا رحمانی(قزوین)", "province_id" => 17, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا الوند(قزوین)", "province_id" => 17, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای گلبهار (مشهد)", "province_id" => 10, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا مسیر نفت (کرمانشاه)", "province_id" => 27, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای  مهران(ایلام)", "province_id" => 6, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا لردگان (شهرکرد)", "province_id" => 24, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید ابوالحسنی(ساری)", "province_id" => 20, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا الهیه پاکدشت (رجایی)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "هایپرمی پلاتین (تهران)", "province_id" => 8, "shop_category_id" => 11, "grade_id" => 4),
            array("title" => "اسپار پاسداران", "province_id" => 8, "shop_category_id" => 6, "grade_id" => 4),
            array("title" => "اتکا شهرک گلستان(شیراز)", "province_id" => 16, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید منتظری(کرمان)", "province_id" => 26, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا الغدیر(کرمان)", "province_id" => 26, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای کهنوج(کرمان)", "province_id" => 26, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای بافت(کرمان)", "province_id" => 26, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید پور جعفری(کرمان)", "province_id" => 26, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید باهنر(کرمان)", "province_id" => 26, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا مالک اشتر(کرمان)", "province_id" => 26, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا کاشانی تربت حیدریه (مشهد)", "province_id" => 10, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "فامیلی سعیدیه(همدان)", "province_id" => 23, "shop_category_id" => 7, "grade_id" => 3),
            array("title" => "اتکا شهدای حفاظت هواپیمایی (فکوری تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید سلیمی پور(رشت)", "province_id" => 30, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "هایپر فامیلی گلشهر (مشهد)", "province_id" => 10, "shop_category_id" => 7, "grade_id" => 4),
            array("title" => "اتکا ولیعصر تربت حیدریه (مشهد)", "province_id" => 10, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "هایپرفامیلی لرستان (خرم آباد)", "province_id" => 19, "shop_category_id" => 7, "grade_id" => 4),
            array("title" => "اتکا شهیدمیرزاقاسمی(خرم آباد)", "province_id" => 19, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای آران و بیدگل (اصفهان)", "province_id" => 4, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای فریمان (مشهد)", "province_id" => 10, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید قنبری (ارومیه)", "province_id" => 2, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "هایپرمی یزد (یزد)", "province_id" => 31, "shop_category_id" => 11, "grade_id" => 3),
            array("title" => "شرکت زنجیره غذایی امیران (بلوار انقلاب)", "province_id" => 5, "shop_category_id" => 5, "grade_id" => 5),
            array("title" => "اتکا امت مشهد (مشهد)", "province_id" => 10, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "شرکت زنجیره غذایی امیران (عظیمیه)", "province_id" => 5, "shop_category_id" => 5, "grade_id" => 6),
            array("title" => "شرکت زنجیره غذایی امیران  (فاز یک اندیشه)", "province_id" => 5, "shop_category_id" => 5, "grade_id" => 6),
            array("title" => "شرکت زنجیره غذایی امیران(بلوار ارم)", "province_id" => 5, "shop_category_id" => 5, "grade_id" => 6),
            array("title" => "شرکت زنجیره غذایی امیران (فاز 4 مهرشهر)", "province_id" => 5, "shop_category_id" => 5, "grade_id" => 5),
            array("title" => "شرکت زنجیره غذایی امیران  (فردیس)", "province_id" => 5, "shop_category_id" => 5, "grade_id" => 6),
            array("title" => "اتکا شهدای لاهیجان(رشت)", "province_id" => 30, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "شرکت زنجیره غذایی امیران(مهرشهر)", "province_id" => 5, "shop_category_id" => 5, "grade_id" => 5),
            array("title" => "شرکت زنجیره غذایی امیران (درختی)", "province_id" => 5, "shop_category_id" => 5, "grade_id" => 6),
            array("title" => "شرکت زنجیره غذایی امیران ملارد (دفتر مرکزی)", "province_id" => 5, "shop_category_id" => 5, "grade_id" => 5),
            array("title" => "شرکت زنجیره غذایی امیران (مشکین دشت)", "province_id" => 5, "shop_category_id" => 5, "grade_id" => 5),
            array("title" => "شرکت زنجیره غذایی امیران(فرهنگیان)", "province_id" => 5, "shop_category_id" => 5, "grade_id" => 5),
            array("title" => "شرکت زنجیره غذایی امیران (باغستان)", "province_id" => 5, "shop_category_id" => 5, "grade_id" => 5),
            array("title" => "شرکت زنجیره غذایی امیران(میدان آزادگان-برغان)", "province_id" => 5, "shop_category_id" => 5, "grade_id" => 5),
            array("title" => "شرکت زنجیره غذایی امیران(کردان)", "province_id" => 5, "shop_category_id" => 5, "grade_id" => 5),
            array("title" => "شرکت زنجیره غذایی امیران( حصارک)", "province_id" => 5, "shop_category_id" => 5, "grade_id" => 5),
            array("title" => "اتکا حکیم نظامی (ارومیه)", "province_id" => 2, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا شهدای خان طومان آمل (ساری)", "province_id" => 20, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "شرکت آتیه فرزندان وطن (پروژه باقری - وال مارکت)", "province_id" => 8, "shop_category_id" => 3, "grade_id" => 4),
            array("title" => "شرکت آتیه فرزندان وطن(پروژه مهراد مال - وال مارکت)", "province_id" => 5, "shop_category_id" => 3, "grade_id" => 3),
            array("title" => "شرکت آتیه فرزندان وطن(پروژه بهشتی - وال مارکت)", "province_id" => 5, "shop_category_id" => 3, "grade_id" => 4),
            array("title" => "هایپر فامیلی رباط کریم(تهران)", "province_id" => 8, "shop_category_id" => 7, "grade_id" => 4),
            array("title" => "هایپرفامیلی ساری(ساری)", "province_id" => 20, "shop_category_id" => 7, "grade_id" => 3),
            array("title" => "هایپرفامیلی بابلسر(بابلسر)", "province_id" => 20, "shop_category_id" => 7, "grade_id" => 4),
            array("title" => "اتکا شهدای مرصاد (کرمانشاه)", "province_id" => 27, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا خدا پرست  (پیشوا)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید نجفی (کرمانشاه)", "province_id" => 27, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای منوجان (بندرعباس)", "province_id" => 22, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا فرانچایز امینی بیات(قم)", "province_id" => 18, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا فرانچایز ناجیان سبز(قم)", "province_id" => 18, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا ولیعصر نجف آباد (ولیعصر نجف آباد)اصفهان", "province_id" => 4, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا طالقانی قوچان (مشهد)", "province_id" => 10, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید باکری (ارومیه)", "province_id" => 2, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "شرکت خدماتی کالای شهروند(علی اکبری-سهروردی)", "province_id" => 8, "shop_category_id" => 1, "grade_id" => 4),
            array("title" => "فامیلی مدرن  سبزوار(مشهد)", "province_id" => 10, "shop_category_id" => 7, "grade_id" => 4),
            array("title" => "فامیلی مدرن الهیه( مشهد)", "province_id" => 10, "shop_category_id" => 7, "grade_id" => 3),
            array("title" => "اتکا شهدای بیست و هشت دی (سنندج)/اتکا زاگرس", "province_id" => 25, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید نوری (شهدای انقلاب)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا بعثت گنبد(گرگان)", "province_id" => 29, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا فرانچایز دلیجان (اراک)", "province_id" => 21, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "هایپرمی سنندج (سنندج)", "province_id" => 25, "shop_category_id" => 11, "grade_id" => 1),
            array("title" => "هایپرمی درختی (کرج)/مهرویلا", "province_id" => 5, "shop_category_id" => 11, "grade_id" => 3),
            array("title" => "اتکا شهرک شهید رسولی (نوبنیاد تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای بهشهر (ساری)", "province_id" => 20, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای زاوه( مشهد)", "province_id" => 10, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "فامیلی چمران کرمان(کرمان)", "province_id" => 26, "shop_category_id" => 7, "grade_id" => 3),
            array("title" => "اتکا جزیره خارک (بوشهر)", "province_id" => 7, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا سردارجنگل لاهیجان (رشت)", "province_id" => 30, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای بندرترکمن(گرگان)", "province_id" => 20, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "شرکت آتیه فرزندان وطن(مترو نبرد - وال مارکت)", "province_id" => 8, "shop_category_id" => 3, "grade_id" => 3),
            array("title" => "اتکا شهید چمران دورود (خرم اباد)", "province_id" => 19, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای بندر گز(گرگان)", "province_id" => 20, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید رضاپور (مهراباد)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهیدان نژاد فلاح (کرج)", "province_id" => 5, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "شرکت کالابهرسان تارا نوین (شیراز)", "province_id" => 16, "shop_category_id" => 15, "grade_id" => 4),
            array("title" => "شرکت کالابهرسان تارا نوین(بندرعباس)", "province_id" => 22, "shop_category_id" => 15, "grade_id" => 4),
            array("title" => "اتکا فاطمیه سیرجان (کرمان)", "province_id" => 26, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید قلیزاده (رجایی تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا رزمندگان ارتش - سامان (پیشوا)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "فامیلی مدرن( رامسر)", "province_id" => 30, "shop_category_id" => 7, "grade_id" => 4),
            array("title" => "شرکت آتیه فرزندان وطن(وال مارکت قزوین)", "province_id" => 17, "shop_category_id" => 3, "grade_id" => 4),
            array("title" => "هایپر استار (یزد)", "province_id" => 31, "shop_category_id" => 2, "grade_id" => 2),
            array("title" => "فرانچایز اتکا قرنی مشهد", "province_id" => 10, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا 2 محمدیه(قزوین)", "province_id" => 17, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا ارباب پور (کرمانشاه)", "province_id" => 27, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا مدرس (کرمانشاه)", "province_id" => 27, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "شرکت آتیه فرزندان وطن(وال مارکت زنجان)", "province_id" => 13, "shop_category_id" => 3, "grade_id" => 4),
            array("title" => "اتکا شهدای آستارا (رشت)", "province_id" => 30, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای دو کوهه اندیمشک(اهواز)", "province_id" => 12, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا بلوار طبرسی (مشهد)", "province_id" => 10, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا محمد رسول الله سعدآباد (بوشهر)", "province_id" => 16, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهرک پژوهش (مشهد)", "province_id" => 10, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکاتالش لیسار(رشت)", "province_id" => 30, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "فامیلی  مدرن امیر کبیر (کرمان)", "province_id" => 26, "shop_category_id" => 7, "grade_id" => 3),
            array("title" => "هایپرمی شیراز", "province_id" => 16, "shop_category_id" => 11, "grade_id" => 1),
            array("title" => "شرکت آتیه فرزندان وطن(وال مارکت توحید)", "province_id" => 5, "shop_category_id" => 3, "grade_id" => 3),
            array("title" => "اتکا شهدای استهبان(شیراز)", "province_id" => 16, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "شرکت آتیه فرزندان وطن(اندیشه - وال مارکت)", "province_id" => 5, "shop_category_id" => 3, "grade_id" => 4),
            array("title" => "اتکا  شهریار(مهرآبادتهران)", "province_id" => 5, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "هایپراستار فدک (اصفهان)", "province_id" => 4, "shop_category_id" => 2, "grade_id" => 1),
            array("title" => "اتکا غفور جدی اردبیل", "province_id" => 3, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "هایپر استار مایلی سوهانک(تهران)", "province_id" => 8, "shop_category_id" => 2, "grade_id" => 4),
            array("title" => "شرکت خدماتی کالای شهروند همت(بشرا)", "province_id" => 8, "shop_category_id" => 1, "grade_id" => 4),
            array("title" => "هایپراستار پارک سنتر(اهواز)", "province_id" => 12, "shop_category_id" => 2, "grade_id" => 1),
            array("title" => "هایپراستار مارکت خلیج فارس (اهواز)", "province_id" => 12, "shop_category_id" => 2, "grade_id" => 3),
            array("title" => "اتکا جانبازان خلخال (اردبیل)", "province_id" => 3, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا مالک اشتر (کرمانشاه)", "province_id" => 27, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا تکاور کرمانشاه", "province_id" => 27, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید زرهرن (", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "فروشگاه اتکا جامی (ارومیه)", "province_id" => 2, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا انبار مرکزی فکوری (فکوری تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 1),
            array("title" => "اتکا شهید حسین لشگری (قزوین)", "province_id" => 17, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "وال مارکت رشت", "province_id" => 30, "shop_category_id" => 3, "grade_id" => 4),
            array("title" => "اتکا سفیر امید تبریز (", "province_id" => 1, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "فروشگاه اتکا شهید دوست زاده اسفراین", "province_id" => 11, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدا کیان (شهرکرد)", "province_id" => 4, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "هایپر فامیلی (طرشت)", "province_id" => 8, "shop_category_id" => 7, "grade_id" => 2),
            array("title" => "اتکا شهید محمد علی صفا (بجنورد)", "province_id" => 11, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا شهید مدرس (/اتکا مدرس شیراز", "province_id" => 16, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای وزارت امور خارجه", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "وال مارکت (استاد معین)", "province_id" => 8, "shop_category_id" => 3, "grade_id" => 4),
            array("title" => "اتکا شهدای رودبار", "province_id" => 30, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "فامیلی مدرن ایلام", "province_id" => 6, "shop_category_id" => 7, "grade_id" => 3),
            array("title" => "وال مارکت بروجرد", "province_id" => 19, "shop_category_id" => 3, "grade_id" => 4),
            array("title" => "اتکا حفاظت اطلاعات (فرودگاه مهرآباد)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا فروشگاه سربازان گمنام(ارومیه)", "province_id" => 2, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا بلوار معلم مرند (آذربایجان شرقی)", "province_id" => 1, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای البرز", "province_id" => 5, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "فامیلی مدرن رویان", "province_id" => 20, "shop_category_id" => 7, "grade_id" => 4),
            array("title" => "اتکا مشارکتی شهدای اقلید ( استان فارس)", "province_id" => 16, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "فروشگاه وال مارکت ساوه", "province_id" => 21, "shop_category_id" => 3, "grade_id" => 4),
            array("title" => "هایپرفامیلی مدرن قزوین", "province_id" => 8, "shop_category_id" => 7, "grade_id" => 4),
            array("title" => "اتکا شهید نورخدا موسوی(خرم آباد)", "province_id" => 19, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای شلمان (رشت)", "province_id" => 30, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکاشهید سعادتمند", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا امام خمینی بوشهر (بندر بوشهر)/چاه مبارک", "province_id" => 7, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای نیرو هوایی ارتش ( قصرفیروزه)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای چناران", "province_id" => 10, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا درگز(مشهد)", "province_id" => 10, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "مایا پیروزی (مشهد)", "province_id" => 10, "shop_category_id" => 8, "grade_id" => 4),
            array("title" => "وال مارکت اصفهان - خیابان میثم", "province_id" => 4, "shop_category_id" => 3, "grade_id" => 4),
            array("title" => "وال مارکت خرم آباد - گلدشت", "province_id" => 19, "shop_category_id" => 3, "grade_id" => 4),
            array("title" => "فروشگاه هایپرفامیلی سامعی (یزد )", "province_id" => 31, "shop_category_id" => 7, "grade_id" => 4),
            array("title" => "اتکا بلوار توس (مشهد)", "province_id" => 10, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "هایپر فامیلی دزفول", "province_id" => 12, "shop_category_id" => 7, "grade_id" => 3),
            array("title" => "فامیلی مدرن بجنورد قیام", "province_id" => 10, "shop_category_id" => 7, "grade_id" => 3),
            array("title" => "فامیلی مدرن بجنورد امیریه", "province_id" => 10, "shop_category_id" => 7, "grade_id" => 3),
            array("title" => "هایپر فامیلی تاکستان (قزوین)", "province_id" => 17, "shop_category_id" => 7, "grade_id" => 3),
            array("title" => "اتکا شهید عباسپور (قصر فیروزه تهران)/اتکا حکیمیه", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای اسلامشهر (رجایی تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "وال مارکت اردبیل", "province_id" => 3, "shop_category_id" => 3, "grade_id" => 4),
            array("title" => "اتکا مشارکتی سلفچگان (قم)", "province_id" => 18, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "هایپرمی رزمال (تهران)", "province_id" => 8, "shop_category_id" => 11, "grade_id" => 3),
            array("title" => "فامیلی رفسنجان 2 (کرمان)", "province_id" => 26, "shop_category_id" => 7, "grade_id" => 4),
            array("title" => "هایپرمی انزلی (گیلان)", "province_id" => 30, "shop_category_id" => 11, "grade_id" => 3),
            array("title" => "اتکا شهید آبشناسان (فکوری تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "وال مارکت زاهدان", "province_id" => 15, "shop_category_id" => 3, "grade_id" => 3),
            array("title" => "اتکا شهدای یافت آباد (فکوری تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا بلوار کاج (فکوری تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "وال مارکت اراک (پارک آزادی)", "province_id" => 21, "shop_category_id" => 3, "grade_id" => 4),
            array("title" => "شرکت زنجیره غذایی امیران (چمن-مهرشهر)", "province_id" => 5, "shop_category_id" => 5, "grade_id" => 5),
            array("title" => "فامیلی جیرفت(استان کرمان)", "province_id" => 26, "shop_category_id" => 7, "grade_id" => 4),
            array("title" => "اتکا شهدای ینگی امام (کرج)/اتکا مدافع حرم", "province_id" => 5, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای دماوند (شهدای انقلاب)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "فامیلی مدرن ورامین (تهران)", "province_id" => 8, "shop_category_id" => 7, "grade_id" => 4),
            array("title" => "اتکا شهدای آق قلا (گرگان)", "province_id" => 29, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای انبارالوم (گرگان)", "province_id" => 29, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید عفیفی پور (شیراز)", "province_id" => 16, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا تاکستان (قزوین)", "province_id" => 17, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا الیاس چگینی (قزوین)", "province_id" => 17, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "هایپرفامیلی مهریز ( یزد)", "province_id" => 31, "shop_category_id" => 7, "grade_id" => 4),
            array("title" => "وال مارکت ماهشهر (خوزستان)", "province_id" => 12, "shop_category_id" => 3, "grade_id" => 4),
            array("title" => "هایپرفامیلی جهاد (کاشان)", "province_id" => 4, "shop_category_id" => 7, "grade_id" => 4),
            array("title" => "اتکا مشارکتی شهید خزلی (فکوری تهران)", "province_id" => 5, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهید حاصلی (خرم آباد)", "province_id" => 19, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "وال مارکت نازی آباد _بازاردوم (تهران)", "province_id" => 8, "shop_category_id" => 3, "grade_id" => 4),
            array("title" => "اتکا شهید صفوی کوهسار (نامجو تهران)", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا امیرکبیرمراغه (مراغه)", "province_id" => 1, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا حضرت رسول جوانرود (کرمانشاه)", "province_id" => 27, "shop_category_id" => 9, "grade_id" => 2),
            array("title" => "هایپرمی اطلس مال (تهران)", "province_id" => 8, "shop_category_id" => 11, "grade_id" => 3),
            array("title" => "اتکا امام حسن مجتیی قشم (قشم)", "province_id" => 22, "shop_category_id" => 9, "grade_id" => 4),
            array("title" => "اتکا شهدای شیرگاه(ساری)", "province_id" => 20, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "اتکا امام زاده حسن", "province_id" => 8, "shop_category_id" => 9, "grade_id" => 3),
            array("title" => "شهروند (وزارت راه)", "province_id" => 8, "shop_category_id" => 1, "grade_id" => 4),
            array("title" => "شرکت خدمات کالای شهروند (چیتگر)", "province_id" => 8, "shop_category_id" => 1, "grade_id" => 3),
            array("title" => "فامیلی مدرن چابهار(سیستان)", "province_id" => 15, "shop_category_id" => 7, "grade_id" => 3),
        );
        foreach ($info as $item){
            \App\Models\Shop::create($item);
        }
    }
}
